version: "3"

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8080:8080"
    networks:
      - bridge_network
    environment:
      - DB_HOST=mongodb://mongodb/BlogApp
      - HASH_SECRET=secret
      - JWT_SECRET=secret_key
    
  mongodb:
    container_name: mongo_database
    image: mongo
    ports:
      - "30000:27017"
    networks:
      - bridge_network
    volumes:
      - BlogApp:/data/db

networks:
  bridge_network:
    driver: bridge

volumes:
  BlogApp:
    driver: local