version: "3"

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8080:8080"
    networks:
      - bridge_network
    environment:
      - NODE_ENV=production

  mongodbService:
    container_name: mongo_database
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - bridge_network
    volumes:
      - BlogApp:/data/db

  redisService:
    container_name: redis_database
    image: redis
    ports:
      - "6379:6379"
    networks:
      - bridge_network
    volumes:
      - redis_data:/data

networks:
  bridge_network:
    driver: bridge

volumes:
  BlogApp:
    driver: local
  redis_data:
    driver: local
